### ISSUE TITLE
Spring Cloud Vault 1.0.x needs jdk8

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-jenkins-jobs#7]
For other hashicorp products we use 7 on master.

https://jenkins.spring.io/blue/organizations/jenkins/spring-cloud-vault-1.0.x-ci/detail/spring-cloud-vault-1.0.x-ci/1475/pipeline

/cc @mp911de

**Comment by mp911de** [comment]
57f3c9578799c020641ad088e411c2cc3012f4a9 introduced the change to build non-2.x branches with JDK7. Spring Cloud Vault uses a newer AssertJ version (3.x) in the tests which requires Java 8 for the build.

**Comment by marcingrzejszczak** [comment]
We're not building this anymore
